
stages:
  - build
  
beforeScript:
  - |
    export PATH=$PWD/node_modules/.bin:/root/.cli:$PATH
    echo $PATH
    tnpm -v
    
build:
  stage: build
  aciTags: DOCKER
  agent:
    docker:
      image: reg.docker.alibaba-inc.com/odc-front/odc-e2e:node14
      resourceRequirements:
        cpu: 4
        memory: 12
        ephemeral-storage: 30
  script:
    - |
      export PATH=$PWD/node_modules/.bin:/root/.cli:$PATH
      node -e "console.log('%j, %j', process.versions, process.execPath)"
      tnpm i @alipay/ob-yuque2book-front -g
      ob-md2book -p ./ -n "${ACI_VAR_docName}" -o ./
      tar -zcvf doc.tar.gz output
  publisher:
    archiveArtifacts:
      artifacts: 'doc.tar.gz'
      allowEmptyArchive: true