1.what-s-new=What's New
10.attachment=Attachment
2.odc-overview=Overview
3.quickstart=Quick Start
4.tutorials=Tutorials
5.web-odc-user-guide=User Guide (Web ODC)
1.log-on-to-odc=Log on to ODC
10.web-odc-database-objects=Database objects
1.web-odc-table-objects=Table objects
2.web-odc-view-objects=View objects
3.web-odc-function-objects=Function objects
4.web-odc-stored-procedure-objects=Stored procedure objects
5.web-odc-sequence-objects=Sequence objects
6.web-odc-package-objects=Package objects
7.web-odc-trigger-objects=Trigger objects
8.web-odc-type-objects=Type objects
9.web-odc-synonym-objects=Synonym objects
3.web-odc-connect-database=Connect to a database
4.web-odc-public-resource-management=Public resource management
2.web-odc-manage-members=Member management
3.web-odc-resource-management=Resource management
5.web-odc-use-workspace=Use the workspace
6.web-odc-use-tools=Use tools
1.web-odc-data-export-and-import=Data export and import
8.web-odc-task-management=Task management
6.client-odc-user-guide=User Guide (Client ODC)
3.client-odc-connect-database=Connect to a database
4.client-odc-use-workspace=Use the workspace
5.client-odc-use-tools=Use tools
1.client-odc-data-export-and-import=Data export and import
7.client-odc-task-management=Task management
9.client-odc-database-objects=Database objects
1.client-odc-table-objects=Table objects
2.client-odc-view-objects=View objects
3.client-odc-function-objects=Function objects
4.client-odc-stored-procedure-objects=Stored procedure objects
5.client-odc-sequence-objects=Sequence objects
6.client-odc-package-objects=Package objects
7.client-odc-trigger-objects=Trigger objects
8.client-odc-type-objects=Type objects
9.client-odc-synonym-objects=Synonym objects
7.deployment-guide=Deployment Guide
3.deploy-a-single-odc-node=Deploy a single ODC node
4.deploy-the-ha-odc=Deploy ODC in high availability mode
8.upgrade-guide=Upgrade Guide
3.upgrade-single-node-odc=Upgrade single-node ODC
4.upgrade-high-availability-odc=Upgrade high-availability 